name = "beabo"
compatibility_date = "2026-03-19"

[vars]
AWS_REGION = "us-east-2"
AWS_BUCKET = "drexmmm"
# Configura estas dos variables como secretos con wrangler:
# wrangler secret put AWS_ACCESS_KEY_ID
# wrangler secret put AWS_SECRET_ACCESS_KEY
